/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supplychains.gui;

import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import supplychains.core.Customer;
import supplychains.core.Supplier;
import supplychains.core.SupplyChains;
import supplychains.core.SupplyChainsLogger;
import supplychains.core.TransportConnection;
import supplychains.core.exceptions.SupplyChainsException;
import supplychains.core.helpers.SupplyChainsUtils;

/**
 *
 * @author Branimir
 */
public class BrokerProblemWindow extends javax.swing.JFrame {

    SupplyChainsLogger logger;
    /**
     * Creates new form BrokerProblemWindow
     */
    public BrokerProblemWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        demandO1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        priceO1 = new javax.swing.JSpinner();
        privilegedO1 = new javax.swing.JCheckBox();
        demandO2 = new javax.swing.JSpinner();
        priceO2 = new javax.swing.JSpinner();
        privilegedO2 = new javax.swing.JCheckBox();
        demandO3 = new javax.swing.JSpinner();
        priceO3 = new javax.swing.JSpinner();
        privilegedO3 = new javax.swing.JCheckBox();
        demandO4 = new javax.swing.JSpinner();
        priceO4 = new javax.swing.JSpinner();
        privilegedO4 = new javax.swing.JCheckBox();
        demandO5 = new javax.swing.JSpinner();
        priceO5 = new javax.swing.JSpinner();
        privilegedO5 = new javax.swing.JCheckBox();
        demandO6 = new javax.swing.JSpinner();
        priceO6 = new javax.swing.JSpinner();
        privilegedO6 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        supplyS1 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        priceS1 = new javax.swing.JSpinner();
        privilegedS1 = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        supplyS2 = new javax.swing.JSpinner();
        priceS2 = new javax.swing.JSpinner();
        privilegedS2 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        supplyS3 = new javax.swing.JSpinner();
        priceS3 = new javax.swing.JSpinner();
        privilegedS3 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        supplyS4 = new javax.swing.JSpinner();
        priceS4 = new javax.swing.JSpinner();
        privilegedS4 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        supplyS5 = new javax.swing.JSpinner();
        priceS5 = new javax.swing.JSpinner();
        privilegedS5 = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        supplyS6 = new javax.swing.JSpinner();
        priceS6 = new javax.swing.JSpinner();
        privilegedS6 = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        connectionsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        transportCost1 = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        transportCost2 = new javax.swing.JSpinner();
        transportCost3 = new javax.swing.JSpinner();
        transportCost4 = new javax.swing.JSpinner();
        transportCost5 = new javax.swing.JSpinner();
        transportCost6 = new javax.swing.JSpinner();
        transportCost7 = new javax.swing.JSpinner();
        transportCost8 = new javax.swing.JSpinner();
        transportCost9 = new javax.swing.JSpinner();
        transportCost10 = new javax.swing.JSpinner();
        transportCost11 = new javax.swing.JSpinner();
        transportCost12 = new javax.swing.JSpinner();
        transportCost13 = new javax.swing.JSpinner();
        transportCost14 = new javax.swing.JSpinner();
        transportCost15 = new javax.swing.JSpinner();
        transportCost16 = new javax.swing.JSpinner();
        transportCost17 = new javax.swing.JSpinner();
        transportCost18 = new javax.swing.JSpinner();
        transportCost19 = new javax.swing.JSpinner();
        transportCost20 = new javax.swing.JSpinner();
        transportCost21 = new javax.swing.JSpinner();
        transportCost22 = new javax.swing.JSpinner();
        transportCost23 = new javax.swing.JSpinner();
        transportCost24 = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        transportCost25 = new javax.swing.JSpinner();
        transportCost26 = new javax.swing.JSpinner();
        transportCost27 = new javax.swing.JSpinner();
        transportCost28 = new javax.swing.JSpinner();
        transportCost29 = new javax.swing.JSpinner();
        transportCost30 = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        transportCost31 = new javax.swing.JSpinner();
        transportCost32 = new javax.swing.JSpinner();
        transportCost33 = new javax.swing.JSpinner();
        transportCost34 = new javax.swing.JSpinner();
        transportCost35 = new javax.swing.JSpinner();
        transportCost36 = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        demandO1.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        jLabel2.setText("Odbiorca:");

        jLabel3.setText("Popyt");

        jLabel4.setText("Cena:");

        jLabel5.setText("Wyróżniony:");

        priceO1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        demandO2.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        priceO2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        demandO3.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        priceO3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        demandO4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        priceO4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        demandO5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        priceO5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        demandO6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        priceO6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel11.setText("D1:");

        supplyS1.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        jLabel12.setText("Dostawca:");

        jLabel13.setText("Podaż:");

        jLabel14.setText("Cena:");

        jLabel15.setText("Wyróżniony:");

        priceS1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel16.setText("D2:");

        supplyS2.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        priceS2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel17.setText("D3:");

        supplyS3.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        priceS3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel18.setText("D4:");

        supplyS4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        priceS4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel19.setText("D5:");

        supplyS5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        priceS5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel20.setText("D6:");

        supplyS6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        priceS6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(privilegedS6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(supplyS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(priceS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(privilegedS1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(privilegedS2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(supplyS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(priceS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(supplyS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)
                                .addComponent(priceS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(privilegedS3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(supplyS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)
                                .addComponent(priceS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(privilegedS4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(supplyS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(priceS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(privilegedS5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplyS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(priceS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplyS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supplyS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplyS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplyS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplyS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplyS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(privilegedS3)
                        .addComponent(privilegedS2)
                        .addComponent(privilegedS4)
                        .addComponent(privilegedS5))
                    .addComponent(privilegedS1)
                    .addComponent(privilegedS6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(demandO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(privilegedO1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(privilegedO2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(demandO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(priceO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(demandO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(priceO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(privilegedO3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(demandO4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(priceO4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(privilegedO4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(demandO5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(priceO5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(privilegedO5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(demandO6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(priceO6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(privilegedO6)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(demandO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(demandO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(demandO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(priceO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(demandO4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceO4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(demandO5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceO5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(demandO6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceO6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(privilegedO3)
                        .addComponent(privilegedO4)
                        .addComponent(privilegedO5)
                        .addComponent(privilegedO6))
                    .addComponent(privilegedO1)
                    .addComponent(privilegedO2))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel21.setText("Macierz kosztów transportu:");

        jLabel1.setText("O1: ");

        jLabel6.setText("O2: ");

        jLabel7.setText("O3: ");

        jLabel8.setText("O4: ");

        jLabel9.setText("O5: ");

        jLabel10.setText("O6: ");

        transportCost1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel22.setText("D1:");

        jLabel23.setText("D2:");

        transportCost2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost7.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost8.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost9.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost10.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost11.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost12.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost13.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost14.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost15.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost16.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost17.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost18.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost19.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost20.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost21.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost22.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost23.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost24.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel24.setText("D3:");

        jLabel25.setText("D4:");

        transportCost25.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost26.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost27.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost28.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost29.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost30.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel26.setText("D5:");

        transportCost31.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost32.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost33.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost34.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost35.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        transportCost36.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel27.setText("D6:");

        javax.swing.GroupLayout connectionsPanelLayout = new javax.swing.GroupLayout(connectionsPanel);
        connectionsPanel.setLayout(connectionsPanelLayout);
        connectionsPanelLayout.setHorizontalGroup(
            connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(connectionsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transportCost1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(transportCost2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(connectionsPanelLayout.createSequentialGroup()
                        .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(connectionsPanelLayout.createSequentialGroup()
                                .addComponent(transportCost13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(transportCost14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(connectionsPanelLayout.createSequentialGroup()
                                .addComponent(transportCost7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(transportCost8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(connectionsPanelLayout.createSequentialGroup()
                                .addComponent(transportCost19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(transportCost20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(connectionsPanelLayout.createSequentialGroup()
                                .addComponent(transportCost25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(transportCost26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(connectionsPanelLayout.createSequentialGroup()
                                .addComponent(transportCost31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(transportCost32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(connectionsPanelLayout.createSequentialGroup()
                        .addComponent(transportCost15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transportCost16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transportCost17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transportCost18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(connectionsPanelLayout.createSequentialGroup()
                        .addComponent(transportCost9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transportCost10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transportCost11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transportCost12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(connectionsPanelLayout.createSequentialGroup()
                        .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transportCost3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transportCost4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transportCost5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(transportCost6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(connectionsPanelLayout.createSequentialGroup()
                        .addComponent(transportCost21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transportCost22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transportCost23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transportCost24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(connectionsPanelLayout.createSequentialGroup()
                        .addComponent(transportCost27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transportCost28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transportCost29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transportCost30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(connectionsPanelLayout.createSequentialGroup()
                        .addComponent(transportCost33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transportCost34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transportCost35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transportCost36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        connectionsPanelLayout.setVerticalGroup(
            connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(connectionsPanelLayout.createSequentialGroup()
                        .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transportCost1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(transportCost2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transportCost3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transportCost4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transportCost5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transportCost6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(transportCost7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(transportCost8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(transportCost9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(transportCost10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(transportCost11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(transportCost12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transportCost13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transportCost19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transportCost25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transportCost31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportCost36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)))
        );

        calculate.setText("Oblicz");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(connectionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calculate)))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(connectionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(calculate))
                .addGap(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        try {
            ArrayList<Supplier> suppliers = getSuppliersList();
            ArrayList<Customer> customers = getCustomersList();
            TransportConnection[][] transportConnections = getTransportConnectionsMatrix(suppliers, customers);
            SupplyChains solver = new SupplyChains();
            solver.setLogger(getLogger());
            solver.setConnections(transportConnections);
            solver.setCustomers(customers);
            solver.setSuppliers(suppliers);
            solver.setBrokerProblem();
            solver.solve();
            showResults(solver.getConnectionCosts());
        } catch (SupplyChainsException ex) {
            Logger.getLogger(BrokerProblemWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_calculateActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrokerProblemWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrokerProblemWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrokerProblemWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrokerProblemWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrokerProblemWindow().setVisible(true);
            }
        });
    }
//*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JPanel connectionsPanel;
    private javax.swing.JSpinner demandO1;
    private javax.swing.JSpinner demandO2;
    private javax.swing.JSpinner demandO3;
    private javax.swing.JSpinner demandO4;
    private javax.swing.JSpinner demandO5;
    private javax.swing.JSpinner demandO6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner priceO1;
    private javax.swing.JSpinner priceO2;
    private javax.swing.JSpinner priceO3;
    private javax.swing.JSpinner priceO4;
    private javax.swing.JSpinner priceO5;
    private javax.swing.JSpinner priceO6;
    private javax.swing.JSpinner priceS1;
    private javax.swing.JSpinner priceS2;
    private javax.swing.JSpinner priceS3;
    private javax.swing.JSpinner priceS4;
    private javax.swing.JSpinner priceS5;
    private javax.swing.JSpinner priceS6;
    private javax.swing.JCheckBox privilegedO1;
    private javax.swing.JCheckBox privilegedO2;
    private javax.swing.JCheckBox privilegedO3;
    private javax.swing.JCheckBox privilegedO4;
    private javax.swing.JCheckBox privilegedO5;
    private javax.swing.JCheckBox privilegedO6;
    private javax.swing.JCheckBox privilegedS1;
    private javax.swing.JCheckBox privilegedS2;
    private javax.swing.JCheckBox privilegedS3;
    private javax.swing.JCheckBox privilegedS4;
    private javax.swing.JCheckBox privilegedS5;
    private javax.swing.JCheckBox privilegedS6;
    private javax.swing.JSpinner supplyS1;
    private javax.swing.JSpinner supplyS2;
    private javax.swing.JSpinner supplyS3;
    private javax.swing.JSpinner supplyS4;
    private javax.swing.JSpinner supplyS5;
    private javax.swing.JSpinner supplyS6;
    private javax.swing.JSpinner transportCost1;
    private javax.swing.JSpinner transportCost10;
    private javax.swing.JSpinner transportCost11;
    private javax.swing.JSpinner transportCost12;
    private javax.swing.JSpinner transportCost13;
    private javax.swing.JSpinner transportCost14;
    private javax.swing.JSpinner transportCost15;
    private javax.swing.JSpinner transportCost16;
    private javax.swing.JSpinner transportCost17;
    private javax.swing.JSpinner transportCost18;
    private javax.swing.JSpinner transportCost19;
    private javax.swing.JSpinner transportCost2;
    private javax.swing.JSpinner transportCost20;
    private javax.swing.JSpinner transportCost21;
    private javax.swing.JSpinner transportCost22;
    private javax.swing.JSpinner transportCost23;
    private javax.swing.JSpinner transportCost24;
    private javax.swing.JSpinner transportCost25;
    private javax.swing.JSpinner transportCost26;
    private javax.swing.JSpinner transportCost27;
    private javax.swing.JSpinner transportCost28;
    private javax.swing.JSpinner transportCost29;
    private javax.swing.JSpinner transportCost3;
    private javax.swing.JSpinner transportCost30;
    private javax.swing.JSpinner transportCost31;
    private javax.swing.JSpinner transportCost32;
    private javax.swing.JSpinner transportCost33;
    private javax.swing.JSpinner transportCost34;
    private javax.swing.JSpinner transportCost35;
    private javax.swing.JSpinner transportCost36;
    private javax.swing.JSpinner transportCost4;
    private javax.swing.JSpinner transportCost5;
    private javax.swing.JSpinner transportCost6;
    private javax.swing.JSpinner transportCost7;
    private javax.swing.JSpinner transportCost8;
    private javax.swing.JSpinner transportCost9;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Supplier> getSuppliersList() {
        ArrayList<Supplier> list = new ArrayList();
        if((int) supplyS1.getValue() > 0) {
            Supplier tmp = new Supplier((int) supplyS1.getValue(), (int) priceS1.getValue());
            tmp.isPrivileged = privilegedS1.isSelected();
            list.add(tmp);
        }
        if((int) supplyS2.getValue() > 0) {
            Supplier tmp = new Supplier((int) supplyS2.getValue(), (int) priceS2.getValue());
            tmp.isPrivileged = privilegedS2.isSelected();
            list.add(tmp);
        }
        if((int) supplyS3.getValue() > 0) {
            Supplier tmp = new Supplier((int) supplyS3.getValue(), (int) priceS3.getValue());
            tmp.isPrivileged = privilegedS3.isSelected();
            list.add(tmp);
        }
        if((int) supplyS4.getValue() > 0) {
            Supplier tmp = new Supplier((int) supplyS4.getValue(), (int) priceS4.getValue());
            tmp.isPrivileged = privilegedS4.isSelected();
            list.add(tmp);
        }
        if((int) supplyS5.getValue() > 0) {
            Supplier tmp = new Supplier((int) supplyS5.getValue(), (int) priceS5.getValue());
            tmp.isPrivileged = privilegedS5.isSelected();
            list.add(tmp);
        }
        if((int) supplyS6.getValue() > 0) {
            Supplier tmp = new Supplier((int) supplyS6.getValue(), (int) priceS6.getValue());
            tmp.isPrivileged = privilegedS6.isSelected();
            list.add(tmp);
        }
        
        return list;
    }

    private ArrayList<Customer> getCustomersList() {       
        ArrayList<Customer> list = new ArrayList();
        if((int) demandO1.getValue() > 0) {
            Customer tmp = new Customer((int) demandO1.getValue(), (int) priceO1.getValue());
            tmp.isPrivileged = privilegedO1.isSelected();
            list.add(tmp);
        }
        if((int) demandO2.getValue() > 0) {
            Customer tmp = new Customer((int) demandO2.getValue(), (int) priceO2.getValue());
            tmp.isPrivileged = privilegedO2.isSelected();
            list.add(tmp);
        }
        if((int) demandO3.getValue() > 0) {
            Customer tmp = new Customer((int) demandO3.getValue(), (int) priceO3.getValue());
            tmp.isPrivileged = privilegedO3.isSelected();
            list.add(tmp);
        }
        if((int) demandO4.getValue() > 0) {
            Customer tmp = new Customer((int) demandO4.getValue(), (int) priceO4.getValue());
            tmp.isPrivileged = privilegedO4.isSelected();
            list.add(tmp);
        }
        if((int) demandO5.getValue() > 0) {
            Customer tmp = new Customer((int) demandO5.getValue(), (int) priceO5.getValue());
            tmp.isPrivileged = privilegedO5.isSelected();
            list.add(tmp);
        }
        if((int) demandO6.getValue() > 0) {
            Customer tmp = new Customer((int) demandO6.getValue(), (int) priceO6.getValue());
            tmp.isPrivileged = privilegedO6.isSelected();
            list.add(tmp);
        }
        
        return list;
    }

    private TransportConnection[][] getTransportConnectionsMatrix(ArrayList<Supplier> suppliers, ArrayList<Customer> customers) {
        int s = suppliers.size();
        int c = customers.size();
        TransportConnection[][] cons = new TransportConnection[suppliers.size()][customers.size()];
        int x,y;
        if(s >= 1) {
            x = 0;
            y = 0;
            if(c >= 1) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost1.getValue(),x,y);
            y = 1;
            if(c >= 2) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost2.getValue(),x,y);
            y = 2;
            if(c >= 3) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost3.getValue(),x,y);
            y = 3;
            if(c >= 4) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost4.getValue(),x,y);
            y = 4;
            if(c >= 5) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost5.getValue(),x,y);
            y = 5;
            if(c >= 6) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost6.getValue(),x,y);
        }
        if(s >= 2) {
            x = 1;
            y = 0;
            if(c >= 1) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost7.getValue(),x,y);
            y = 1;
            if(c >= 2) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost8.getValue(),x,y);
            y = 2;
            if(c >= 3) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost9.getValue(),x,y);
            y = 3;
            if(c >= 4) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost10.getValue(),x,y);
            y = 4;
            if(c >= 5) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost11.getValue(),x,y);
            y = 5;
            if(c >= 6) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost12.getValue(),x,y);
        }
        if(s >= 3) {
            x = 2;
            y = 0;
            if(c >= 1) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost13.getValue(),x,y);
            y = 1;
            if(c >= 2) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost14.getValue(),x,y);
            y = 2;
            if(c >= 3) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost15.getValue(),x,y);
            y = 3;
            if(c >= 4) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost16.getValue(),x,y);
            y = 4;
            if(c >= 5) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost17.getValue(),x,y);
            y = 5;
            if(c >= 6) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost18.getValue(),x,y);
        }
        if(s >= 4) {
            x = 3;
            y = 0;
            if(c >= 1) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost19.getValue(),x,y);
            y = 1;
            if(c >= 2) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost20.getValue(),x,y);
            y = 2;
            if(c >= 3) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost21.getValue(),x,y);
            y = 3;
            if(c >= 4) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost22.getValue(),x,y);
            y = 4;
            if(c >= 5) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost23.getValue(),x,y);
            y = 5;
            if(c >= 6) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost24.getValue(),x,y);
        }
        if(s >= 5) {
            x = 4;
            y = 0;
            if(c >= 1) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost25.getValue(),x,y);
            y = 1;
            if(c >= 2) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost26.getValue(),x,y);
            y = 2;
            if(c >= 3) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost27.getValue(),x,y);
            y = 3;
            if(c >= 4) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost28.getValue(),x,y);
            y = 4;
            if(c >= 5) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost29.getValue(),x,y);
            y = 5;
            if(c >= 6) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost30.getValue(),x,y);
        }
        if(s >= 6) {
            x = 5;
            y = 0;
            if(c >= 1) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost31.getValue(),x,y);
            y = 1;
            if(c >= 2) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost32.getValue(),x,y);
            y = 2;
            if(c >= 3) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost33.getValue(),x,y);
            y = 3;
            if(c >= 4) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost34.getValue(),x,y);
            y = 4;
            if(c >= 5) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost35.getValue(),x,y);
            y = 5;
            if(c >= 6) cons[x][y] = new TransportConnection(suppliers.get(x), customers.get(y), (int)transportCost36.getValue(),x,y);
        }
        return cons;
    }

    private void showResults(TransportConnection[][] matrix) {
        String results = "";        
        int N = matrix.length;
        int M = matrix[0].length;
        
        results += "\nIlości:\n";
        for(int i = 0; i < N; i++) {
            for(int j = 0; j < M; j++) {
                results += String.format("%5d", (int)matrix[i][j].amount);
            }
            results += "\n";
        }
        
        results += "\nZyski jednoskowe:\n";
        for(int i = 0; i < N; i++) {
            for(int j = 0; j < M; j++) {
                results += String.format("%5d", (int)matrix[i][j].unitProfit());
            }
            results += "\n";
        }
        
        results += "\n";
        results += "Zysk = " + SupplyChainsUtils.countTotalProfit(matrix);
        results += "\n";
        
        JFrame jf = new JFrame();
        JTextArea jta = new JTextArea();
        jta.setText(results);
        jta.setFont(Font.getFont(Font.SERIF));
        jf.add(jta);
        jf.setSize(200, 500);
        jf.setVisible(true);
    }

    private SupplyChainsLogger getLogger() {
        if(logger != null) return logger;
        logger = new SupplyChainsLogger() {
            @Override
            public void info(String s) {
                System.out.println(s);
            }
            
            @Override
            public void error(String s, Exception e) {
                System.out.println(s);
                System.out.println(e.getMessage());
            }
        };
        return logger;
    }
}
