/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supplychains.gui;

import javax.swing.JFrame;

/**
 *
 * @author Branimir
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        //newBrokerProblem.setVisible(false);
        //newTransportProblem.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newTransportProblem = new javax.swing.JButton();
        newBrokerProblem = new javax.swing.JButton();
        newTwoStepsProblem = new javax.swing.JButton();
        newMultiStepsProblem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newTransportProblem.setText("Transport Problem");
        newTransportProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTransportProblemActionPerformed(evt);
            }
        });

        newBrokerProblem.setText("Broker Problem");
        newBrokerProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBrokerProblemActionPerformed(evt);
            }
        });

        newTwoStepsProblem.setText("2 Step Problem");
        newTwoStepsProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTwoStepsProblemActionPerformed(evt);
            }
        });

        newMultiStepsProblem.setText("Multi Step Problem");
        newMultiStepsProblem.setActionCommand("Multi Step Problem");
        newMultiStepsProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMultiStepsProblemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(newTransportProblem))
                    .addComponent(newBrokerProblem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newTwoStepsProblem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newMultiStepsProblem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(newTwoStepsProblem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newTransportProblem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newBrokerProblem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newMultiStepsProblem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newTransportProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTransportProblemActionPerformed
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransportProblemWindow().setVisible(true);
            }
        });
    }//GEN-LAST:event_newTransportProblemActionPerformed

    private void newBrokerProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBrokerProblemActionPerformed
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrokerProblemWindow().setVisible(true);
            }
        });
    }//GEN-LAST:event_newBrokerProblemActionPerformed

    private void newTwoStepsProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTwoStepsProblemActionPerformed
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TwoStepsProblemWindow().setVisible(true);
            }
        });
    }//GEN-LAST:event_newTwoStepsProblemActionPerformed

    private void newMultiStepsProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMultiStepsProblemActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultipleStepsProblemWindow().setVisible(true);
            }
        });
    }//GEN-LAST:event_newMultiStepsProblemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton newBrokerProblem;
    private javax.swing.JButton newMultiStepsProblem;
    private javax.swing.JButton newTransportProblem;
    private javax.swing.JButton newTwoStepsProblem;
    // End of variables declaration//GEN-END:variables
}
