/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supplychains.gui;

import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.TableColumn;
import supplychains.core.Customer;
import supplychains.core.Supplier;
import supplychains.core.SupplyChains;
import supplychains.core.SupplyChainsLogger;
import supplychains.core.TransportConnection;
import supplychains.core.exceptions.SupplyChainsException;
import supplychains.core.helpers.SupplyChainsUtils;

/**
 *
 * @author Branimir
 */
public class TransportProblemWindow extends javax.swing.JFrame {

    private SupplyChainsLogger logger;
    private JSpinner[] spinSuppliersSupply;
    private JSpinner[] spinCustomersDemand;
    private JCheckBox[] cbSuppliersPrivilages;
    private JCheckBox[] cbCustomersPrivilages;
    private JSpinner[][] spinConnections;
    private int N = 6, M = 6;
    /**
     * Creates new form TransportProblemWindow
     */
    
    public TransportProblemWindow() {
        initComponents();
        spinSuppliersSupply = new JSpinner[]{supplyS1,supplyS2,supplyS3,supplyS4,supplyS5,supplyS6};
        spinCustomersDemand = new JSpinner[]{demandO1,demandO2,demandO3,demandO4,demandO5,demandO6};
        cbSuppliersPrivilages = new JCheckBox[]{privilegedS1,privilegedS2,privilegedS3,privilegedS4,privilegedS5,privilegedS6};
        cbCustomersPrivilages = new JCheckBox[]{privilegedO1,privilegedO2,privilegedO3,privilegedO4,privilegedO5,privilegedO6};
        spinConnections = new JSpinner[][] {{tc1,tc2,tc3,tc4,tc5,tc6},
                                            {tc7,tc8,tc9,tc10,tc11,tc12},
                                            {tc13,tc14,tc15,tc16,tc17,tc18},
                                            {tc19,tc20,tc21,tc22,tc23,tc24},
                                            {tc25,tc26,tc27,tc28,tc29,tc30},
                                            {tc31,tc32,tc33,tc34,tc35,tc36}};     
        
        refreshGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        suppliersNumber = new javax.swing.JSpinner();
        customersNumber = new javax.swing.JSpinner();
        resetButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        demandO1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        privilegedO1 = new javax.swing.JCheckBox();
        demandO2 = new javax.swing.JSpinner();
        privilegedO2 = new javax.swing.JCheckBox();
        demandO3 = new javax.swing.JSpinner();
        privilegedO3 = new javax.swing.JCheckBox();
        demandO4 = new javax.swing.JSpinner();
        privilegedO4 = new javax.swing.JCheckBox();
        demandO5 = new javax.swing.JSpinner();
        privilegedO5 = new javax.swing.JCheckBox();
        demandO6 = new javax.swing.JSpinner();
        privilegedO6 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        supplyS1 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        privilegedS1 = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        supplyS2 = new javax.swing.JSpinner();
        privilegedS2 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        supplyS3 = new javax.swing.JSpinner();
        privilegedS3 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        supplyS4 = new javax.swing.JSpinner();
        privilegedS4 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        supplyS5 = new javax.swing.JSpinner();
        privilegedS5 = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        supplyS6 = new javax.swing.JSpinner();
        privilegedS6 = new javax.swing.JCheckBox();
        calculate = new javax.swing.JButton();
        connectionsPanel2 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        tc1 = new javax.swing.JSpinner();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        tc2 = new javax.swing.JSpinner();
        tc3 = new javax.swing.JSpinner();
        tc4 = new javax.swing.JSpinner();
        tc5 = new javax.swing.JSpinner();
        tc6 = new javax.swing.JSpinner();
        tc7 = new javax.swing.JSpinner();
        tc8 = new javax.swing.JSpinner();
        tc9 = new javax.swing.JSpinner();
        tc10 = new javax.swing.JSpinner();
        tc11 = new javax.swing.JSpinner();
        tc12 = new javax.swing.JSpinner();
        tc13 = new javax.swing.JSpinner();
        tc14 = new javax.swing.JSpinner();
        tc15 = new javax.swing.JSpinner();
        tc16 = new javax.swing.JSpinner();
        tc17 = new javax.swing.JSpinner();
        tc18 = new javax.swing.JSpinner();
        tc19 = new javax.swing.JSpinner();
        tc20 = new javax.swing.JSpinner();
        tc21 = new javax.swing.JSpinner();
        tc22 = new javax.swing.JSpinner();
        tc23 = new javax.swing.JSpinner();
        tc24 = new javax.swing.JSpinner();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        tc25 = new javax.swing.JSpinner();
        tc26 = new javax.swing.JSpinner();
        tc27 = new javax.swing.JSpinner();
        tc28 = new javax.swing.JSpinner();
        tc29 = new javax.swing.JSpinner();
        tc30 = new javax.swing.JSpinner();
        jLabel54 = new javax.swing.JLabel();
        tc31 = new javax.swing.JSpinner();
        tc32 = new javax.swing.JSpinner();
        tc33 = new javax.swing.JSpinner();
        tc34 = new javax.swing.JSpinner();
        tc35 = new javax.swing.JSpinner();
        tc36 = new javax.swing.JSpinner();
        jLabel55 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Rozmiar");

        suppliersNumber.setModel(new javax.swing.SpinnerNumberModel(3, 1, 6, 1));

        customersNumber.setModel(new javax.swing.SpinnerNumberModel(3, 1, 6, 1));

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        demandO1.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        jLabel2.setText("Odbiorca:");

        jLabel3.setText("Popyt");

        jLabel5.setText("Wyróżniony:");

        demandO2.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        demandO3.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        demandO4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        demandO5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        demandO6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel14.setText("O1:");

        jLabel21.setText("O2:");

        jLabel22.setText("O3:");

        jLabel23.setText("O4:");

        jLabel24.setText("O5:");

        jLabel25.setText("O6:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(privilegedO1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(demandO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(demandO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21))
                    .addComponent(privilegedO2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(demandO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22))
                    .addComponent(privilegedO3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(demandO4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23))
                    .addComponent(privilegedO4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(demandO5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addComponent(privilegedO5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(demandO6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(privilegedO6)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel21)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23)
                        .addComponent(jLabel24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(demandO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(demandO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(demandO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(demandO4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(demandO5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(demandO6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(privilegedO5)
                    .addComponent(privilegedO4)
                    .addComponent(privilegedO3)
                    .addComponent(privilegedO2)
                    .addComponent(privilegedO6)
                    .addComponent(privilegedO1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setText("D1:");

        supplyS1.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        jLabel12.setText("Dostawca:");

        jLabel13.setText("Podaż:");

        jLabel15.setText("Wyróżniony:");

        jLabel16.setText("D2:");

        supplyS2.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        jLabel17.setText("D3:");

        supplyS3.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        jLabel18.setText("D4:");

        supplyS4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel19.setText("D5:");

        supplyS5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel20.setText("D6:");

        supplyS6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(privilegedS6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(privilegedS1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(supplyS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(privilegedS2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(supplyS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(supplyS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))
                            .addComponent(privilegedS3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(supplyS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18))
                            .addComponent(privilegedS4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(supplyS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19))
                            .addComponent(privilegedS5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplyS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(supplyS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(supplyS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(supplyS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(supplyS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(supplyS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(supplyS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(privilegedS2)
                                    .addComponent(privilegedS3)
                                    .addComponent(privilegedS4)
                                    .addComponent(privilegedS5)
                                    .addComponent(privilegedS6)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel15))))
                    .addComponent(privilegedS1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        calculate.setText("Oblicz");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        jLabel44.setText("O1: ");

        jLabel45.setText("O2: ");

        jLabel46.setText("O3: ");

        jLabel47.setText("O4: ");

        jLabel48.setText("O5: ");

        jLabel49.setText("O6: ");

        tc1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel50.setText("D1:");

        jLabel51.setText("D2:");

        tc2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc7.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc8.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc9.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc10.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc11.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc12.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc13.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc14.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc15.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc16.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc17.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc18.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc19.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc20.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc21.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc22.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc23.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc24.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel52.setText("D3:");

        jLabel53.setText("D4:");

        tc25.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc26.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc27.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc28.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc29.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc30.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel54.setText("D5:");

        tc31.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc32.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc33.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc34.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc35.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tc36.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel55.setText("D6:");

        javax.swing.GroupLayout connectionsPanel2Layout = new javax.swing.GroupLayout(connectionsPanel2);
        connectionsPanel2.setLayout(connectionsPanel2Layout);
        connectionsPanel2Layout.setHorizontalGroup(
            connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectionsPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(connectionsPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44))
                        .addGap(18, 18, 18)
                        .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addComponent(tc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(connectionsPanel2Layout.createSequentialGroup()
                        .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel53)
                            .addComponent(jLabel54)
                            .addComponent(jLabel55)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(connectionsPanel2Layout.createSequentialGroup()
                                .addComponent(tc13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tc14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(connectionsPanel2Layout.createSequentialGroup()
                                .addComponent(tc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(connectionsPanel2Layout.createSequentialGroup()
                                .addComponent(tc19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tc20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(connectionsPanel2Layout.createSequentialGroup()
                                .addComponent(tc25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tc26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(connectionsPanel2Layout.createSequentialGroup()
                                .addComponent(tc31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tc32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(connectionsPanel2Layout.createSequentialGroup()
                        .addComponent(tc15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tc16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tc17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tc18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(connectionsPanel2Layout.createSequentialGroup()
                        .addComponent(tc9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tc10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tc11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tc12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(connectionsPanel2Layout.createSequentialGroup()
                        .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46))
                        .addGap(18, 18, 18)
                        .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47))
                        .addGap(18, 18, 18)
                        .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48))
                        .addGap(18, 18, 18)
                        .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49)
                            .addComponent(tc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(connectionsPanel2Layout.createSequentialGroup()
                        .addComponent(tc21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tc22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tc23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tc24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(connectionsPanel2Layout.createSequentialGroup()
                        .addComponent(tc27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tc28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tc29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tc30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(connectionsPanel2Layout.createSequentialGroup()
                        .addComponent(tc33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tc34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tc35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tc36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        connectionsPanel2Layout.setVerticalGroup(
            connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectionsPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(connectionsPanel2Layout.createSequentialGroup()
                        .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45)
                            .addComponent(jLabel46)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48)
                            .addComponent(jLabel49))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel50)
                            .addComponent(tc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tc9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tc10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tc11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tc12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel51)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tc13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tc19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tc25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(connectionsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tc31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tc36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55)))
        );

        logArea.setColumns(20);
        logArea.setRows(5);
        jScrollPane1.setViewportView(logArea);

        jLabel4.setText("Jednostkowe koszty transportu:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(suppliersNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(customersNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resetButton)
                                .addGap(26, 26, 26)
                                .addComponent(calculate))
                            .addComponent(connectionsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(suppliersNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customersNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetButton)
                            .addComponent(calculate))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(connectionsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        refreshGUI();        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        try {
            ArrayList<Supplier> suppliers = getSuppliersList();
            ArrayList<Customer> customers = getCustomersList();
            TransportConnection[][] transportConnections = getTransportConnectionsMatrix(suppliers, customers);
            SupplyChains solver = new SupplyChains();
            solver.setLogger(getLogger());
            solver.setConnections(transportConnections);
            solver.setCustomers(customers);
            solver.setSuppliers(suppliers);
            solver.solve();
            showResults(solver.getConnectionCosts());
        } catch (SupplyChainsException ex) {
            Logger.getLogger(BrokerProblemWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_calculateActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransportProblemWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransportProblemWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransportProblemWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransportProblemWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransportProblemWindow().setVisible(true);
            }
        });
    }
    //*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JPanel connectionsPanel2;
    private javax.swing.JSpinner customersNumber;
    private javax.swing.JSpinner demandO1;
    private javax.swing.JSpinner demandO2;
    private javax.swing.JSpinner demandO3;
    private javax.swing.JSpinner demandO4;
    private javax.swing.JSpinner demandO5;
    private javax.swing.JSpinner demandO6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea logArea;
    private javax.swing.JCheckBox privilegedO1;
    private javax.swing.JCheckBox privilegedO2;
    private javax.swing.JCheckBox privilegedO3;
    private javax.swing.JCheckBox privilegedO4;
    private javax.swing.JCheckBox privilegedO5;
    private javax.swing.JCheckBox privilegedO6;
    private javax.swing.JCheckBox privilegedS1;
    private javax.swing.JCheckBox privilegedS2;
    private javax.swing.JCheckBox privilegedS3;
    private javax.swing.JCheckBox privilegedS4;
    private javax.swing.JCheckBox privilegedS5;
    private javax.swing.JCheckBox privilegedS6;
    private javax.swing.JButton resetButton;
    private javax.swing.JSpinner suppliersNumber;
    private javax.swing.JSpinner supplyS1;
    private javax.swing.JSpinner supplyS2;
    private javax.swing.JSpinner supplyS3;
    private javax.swing.JSpinner supplyS4;
    private javax.swing.JSpinner supplyS5;
    private javax.swing.JSpinner supplyS6;
    private javax.swing.JSpinner tc1;
    private javax.swing.JSpinner tc10;
    private javax.swing.JSpinner tc11;
    private javax.swing.JSpinner tc12;
    private javax.swing.JSpinner tc13;
    private javax.swing.JSpinner tc14;
    private javax.swing.JSpinner tc15;
    private javax.swing.JSpinner tc16;
    private javax.swing.JSpinner tc17;
    private javax.swing.JSpinner tc18;
    private javax.swing.JSpinner tc19;
    private javax.swing.JSpinner tc2;
    private javax.swing.JSpinner tc20;
    private javax.swing.JSpinner tc21;
    private javax.swing.JSpinner tc22;
    private javax.swing.JSpinner tc23;
    private javax.swing.JSpinner tc24;
    private javax.swing.JSpinner tc25;
    private javax.swing.JSpinner tc26;
    private javax.swing.JSpinner tc27;
    private javax.swing.JSpinner tc28;
    private javax.swing.JSpinner tc29;
    private javax.swing.JSpinner tc3;
    private javax.swing.JSpinner tc30;
    private javax.swing.JSpinner tc31;
    private javax.swing.JSpinner tc32;
    private javax.swing.JSpinner tc33;
    private javax.swing.JSpinner tc34;
    private javax.swing.JSpinner tc35;
    private javax.swing.JSpinner tc36;
    private javax.swing.JSpinner tc4;
    private javax.swing.JSpinner tc5;
    private javax.swing.JSpinner tc6;
    private javax.swing.JSpinner tc7;
    private javax.swing.JSpinner tc8;
    private javax.swing.JSpinner tc9;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Supplier> getSuppliersList() {
        int n = (int) suppliersNumber.getValue();
        ArrayList<Supplier> list = new ArrayList();
        for(int i = 0; i < n; i++) {
            Supplier s = new Supplier((int)spinSuppliersSupply[i].getValue(), 0);
            s.isPrivileged = cbSuppliersPrivilages[i].isSelected();
            list.add(s);
        }
        return list;
    }

    private ArrayList<Customer> getCustomersList() {  
        int m = (int) customersNumber.getValue();
        ArrayList<Customer> list = new ArrayList();
        for(int i = 0; i < m; i++) {
            Customer c = new Customer((int)spinCustomersDemand[i].getValue(), 0);
            c.isPrivileged = cbCustomersPrivilages[i].isSelected();
            list.add(c);
        }
        return list;
    }

    private TransportConnection[][] getTransportConnectionsMatrix(ArrayList<Supplier> suppliers, ArrayList<Customer> customers) {
        int n = (int) suppliersNumber.getValue();
        int m = (int) customersNumber.getValue();
        TransportConnection[][] cons = new TransportConnection[n][m];
        for(int i = 0; i < n; i++) {
            for(int j = 0; j < m; j++) {
                cons[i][j] = new TransportConnection(suppliers.get(i), customers.get(j), (int)spinConnections[i][j].getValue(),i,j);
            }
        }
        return cons;
    }

    private void showResults(TransportConnection[][] matrix) {
        String results = "\n\n======\nWyniki\n======\n";        
        int N = matrix.length;
        int M = matrix[0].length;
        
        results += "\nIlości:\n";
        for(int i = 0; i < N; i++) {
            for(int j = 0; j < M; j++) {
                results += String.format("%5d", (int)matrix[i][j].amount);
            }
            results += "\n";
        }
        /*
        results += "\nZyski jednoskowe:\n";
        for(int i = 0; i < N; i++) {
            for(int j = 0; j < M; j++) {
                results += String.format("%5d", (int)matrix[i][j].unitProfit());
            }
            results += "\n";
        }
        */
        results += "\n";
        results += "Koszty = " + SupplyChainsUtils.countTotalCosts(matrix);
        results += "\n";
        
        getLogger().info(results);
//        JFrame jf = new JFrame();
//        JTextArea jta = new JTextArea();
//        jta.setText(results);
//        jta.setFont(Font.getFont(Font.SERIF));
//        jf.add(jta);
//        jf.setSize(700, 500);
//        jf.setVisible(true);
    }

    private void refreshGUI() {
        int n = (int) suppliersNumber.getValue();
        int m = (int) customersNumber.getValue();
        for(int i = 0; i < N; i++) {
            for(int j = 0; j < M; j++) {                
                if(i < n && j < m) spinConnections[i][j].setEnabled(true);
                else spinConnections[i][j].setEnabled(false);
            }
        }
        for(int i = 0; i < N; i++) {               
            if(i < n) spinSuppliersSupply[i].setEnabled(true);
            else spinSuppliersSupply[i].setEnabled(false);
            if(i < n) cbSuppliersPrivilages[i].setEnabled(true);
            else cbSuppliersPrivilages[i].setEnabled(false);
        }
        for(int i = 0; i < M; i++) {               
            if(i < m) spinCustomersDemand[i].setEnabled(true);
            else spinCustomersDemand[i].setEnabled(false);
            if(i < m) cbCustomersPrivilages[i].setEnabled(true);
            else cbCustomersPrivilages[i].setEnabled(false);
        }
    }

    private SupplyChainsLogger getLogger() {
        if(logger != null) return logger;
        logger = new SupplyChainsLogger() {
            @Override
            public void info(String s) {
                logArea.setText(logArea.getText() + s + "\n");
                System.out.println(s);
            }
            
            @Override
            public void error(String s, Exception e) {
                logArea.setText(logArea.getText() + s + "\n");
                logArea.setText(logArea.getText() + e.getMessage() + "\n");
                System.out.println(s);
                System.out.println(e.getMessage());
            }
        };
        return logger;
    }
}
