/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supplychains.gui;

import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.TableColumn;
import supplychains.core.Customer;
import supplychains.core.Supplier;
import supplychains.core.SupplyChains;
import supplychains.core.SupplyChainsLogger;
import supplychains.core.TransportConnection;
import supplychains.core.exceptions.SupplyChainsException;
import supplychains.core.helpers.SupplyChainsUtils;

/**
 *
 * @author Branimir
 */
public class TwoStepsProblemWindow extends javax.swing.JFrame {

    private SupplyChainsLogger logger;
    private JSpinner[] spinSuppliersSupply;
    private JSpinner[] spinSellersDemandSupply;
    private JSpinner[] spinCustomersDemand;
    private JSpinner[][] spinConnectionsSS;
    private JSpinner[][] spinConnectionsSC;
    private final int N = 3, M = 3, L=3;
    /**
     * Creates new form TransportProblemWindow
     */
    
    public TwoStepsProblemWindow() {
        initComponents();
        spinSuppliersSupply = new JSpinner[]{supplyS1,supplyS2,supplyS3};
        spinSellersDemandSupply = new JSpinner[]{demandSupplyS1,demandSupplyS2,demandSupplyS3};
        spinCustomersDemand = new JSpinner[]{demandO1,demandO2,demandO3};
        spinConnectionsSS = new JSpinner[][] {{tcSS11,tcSS12,tcSS13},
                                            {tcSS21,tcSS22,tcSS23},
                                            {tcSS31,tcSS32,tcSS33}}; 
        spinConnectionsSC = new JSpinner[][] {{tcSC11,tcSC12,tcSC13},
                                            {tcSC21,tcSC22,tcSC23},
                                            {tcSC31,tcSC32,tcSC33}};     
        
        refreshGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        suppliersNumber = new javax.swing.JSpinner();
        sellersNumber = new javax.swing.JSpinner();
        resetButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        demandO1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        demandO2 = new javax.swing.JSpinner();
        demandO3 = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        supplyS1 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        supplyS2 = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        supplyS3 = new javax.swing.JSpinner();
        calculate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        customersNumber = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        demandSupplyS1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        demandSupplyS2 = new javax.swing.JSpinner();
        demandSupplyS3 = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        connectionsPanel3 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        tcSS11 = new javax.swing.JSpinner();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        tcSS12 = new javax.swing.JSpinner();
        tcSS13 = new javax.swing.JSpinner();
        tcSS21 = new javax.swing.JSpinner();
        tcSS22 = new javax.swing.JSpinner();
        tcSS23 = new javax.swing.JSpinner();
        tcSS31 = new javax.swing.JSpinner();
        tcSS32 = new javax.swing.JSpinner();
        tcSS33 = new javax.swing.JSpinner();
        jLabel64 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        connectionsPanel4 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        tcSC11 = new javax.swing.JSpinner();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        tcSC12 = new javax.swing.JSpinner();
        tcSC13 = new javax.swing.JSpinner();
        tcSC21 = new javax.swing.JSpinner();
        tcSC22 = new javax.swing.JSpinner();
        tcSC23 = new javax.swing.JSpinner();
        tcSC31 = new javax.swing.JSpinner();
        tcSC32 = new javax.swing.JSpinner();
        tcSC33 = new javax.swing.JSpinner();
        jLabel67 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        isSellerStorage = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Rozmiar");

        suppliersNumber.setModel(new javax.swing.SpinnerNumberModel(2, 1, 3, 1));

        sellersNumber.setModel(new javax.swing.SpinnerNumberModel(2, 1, 3, 1));

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        demandO1.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        jLabel2.setText("Odbiorca:");

        jLabel3.setText("Popyt");

        demandO2.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        demandO3.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        jLabel14.setText("O1:");

        jLabel21.setText("O2:");

        jLabel22.setText("O3:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel21)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel22)
                        .addGap(224, 224, 224))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(demandO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(demandO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(demandO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel21)
                        .addComponent(jLabel22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(demandO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(demandO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(demandO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setText("D1:");

        supplyS1.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        jLabel12.setText("Dostawca:");

        jLabel13.setText("Podaż:");

        jLabel16.setText("D2:");

        supplyS2.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        jLabel17.setText("D3:");

        supplyS3.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supplyS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supplyS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supplyS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplyS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supplyS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplyS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        calculate.setText("Oblicz");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        logArea.setColumns(20);
        logArea.setRows(5);
        jScrollPane1.setViewportView(logArea);

        jLabel4.setText("Jednostkowe koszty transportu:");

        customersNumber.setModel(new javax.swing.SpinnerNumberModel(2, 1, 3, 1));

        demandSupplyS1.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        jLabel6.setText("Handlowiec");

        jLabel7.setText("Popyt/podaz");

        demandSupplyS2.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        demandSupplyS3.setModel(new javax.swing.SpinnerNumberModel(1, 0, 999, 1));

        jLabel26.setText("O1:");

        jLabel27.setText("O2:");

        jLabel28.setText("O3:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(demandSupplyS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(demandSupplyS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(demandSupplyS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(195, 195, 195))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(jLabel27)
                        .addComponent(jLabel28))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(demandSupplyS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(demandSupplyS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(demandSupplyS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel56.setText("H1: ");

        jLabel57.setText("H2: ");

        jLabel58.setText("H3: ");

        tcSS11.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel62.setText("D1:");

        jLabel63.setText("D2:");

        tcSS12.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tcSS13.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tcSS21.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tcSS22.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tcSS23.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tcSS31.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tcSS32.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tcSS33.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel64.setText("D3:");

        jLabel9.setText("Dostawcy vs handlowcy:");

        javax.swing.GroupLayout connectionsPanel3Layout = new javax.swing.GroupLayout(connectionsPanel3);
        connectionsPanel3.setLayout(connectionsPanel3Layout);
        connectionsPanel3Layout.setHorizontalGroup(
            connectionsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectionsPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(connectionsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(connectionsPanel3Layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addGroup(connectionsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(connectionsPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel62)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(connectionsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tcSS11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel56))
                                .addGap(18, 18, 18)
                                .addGroup(connectionsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel57)
                                    .addComponent(tcSS12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(connectionsPanel3Layout.createSequentialGroup()
                                .addGroup(connectionsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel63)
                                    .addComponent(jLabel64))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(connectionsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(connectionsPanel3Layout.createSequentialGroup()
                                        .addComponent(tcSS31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tcSS32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(connectionsPanel3Layout.createSequentialGroup()
                                        .addComponent(tcSS21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tcSS22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(connectionsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tcSS33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tcSS23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tcSS13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel58)))
                    .addGroup(connectionsPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        connectionsPanel3Layout.setVerticalGroup(
            connectionsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectionsPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(connectionsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(connectionsPanel3Layout.createSequentialGroup()
                        .addGroup(connectionsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel56)
                            .addComponent(jLabel57)
                            .addComponent(jLabel58))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(connectionsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tcSS11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel62)
                            .addComponent(tcSS12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tcSS13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(connectionsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tcSS21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tcSS22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tcSS23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel63)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(connectionsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcSS31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcSS32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcSS33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64))
                .addGap(78, 78, 78))
        );

        jLabel59.setText("O1:");

        jLabel60.setText("O2:");

        jLabel61.setText("O3:");

        tcSC11.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel65.setText("H1");

        jLabel66.setText("H2");

        tcSC12.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tcSC13.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tcSC21.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tcSC22.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tcSC23.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tcSC31.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tcSC32.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        tcSC33.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel67.setText("H3");

        jLabel10.setText("Handlowcy vs Odbiorcy");

        javax.swing.GroupLayout connectionsPanel4Layout = new javax.swing.GroupLayout(connectionsPanel4);
        connectionsPanel4.setLayout(connectionsPanel4Layout);
        connectionsPanel4Layout.setHorizontalGroup(
            connectionsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectionsPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(connectionsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(connectionsPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(connectionsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(connectionsPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel65)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(connectionsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tcSC11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel59))
                                .addGap(18, 18, 18)
                                .addGroup(connectionsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel60)
                                    .addComponent(tcSC12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(connectionsPanel4Layout.createSequentialGroup()
                                .addGroup(connectionsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel66)
                                    .addComponent(jLabel67))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(connectionsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(connectionsPanel4Layout.createSequentialGroup()
                                        .addComponent(tcSC31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tcSC32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(connectionsPanel4Layout.createSequentialGroup()
                                        .addComponent(tcSC21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tcSC22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(connectionsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tcSC33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tcSC23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tcSC13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel61)))
                    .addGroup(connectionsPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        connectionsPanel4Layout.setVerticalGroup(
            connectionsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectionsPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(connectionsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(connectionsPanel4Layout.createSequentialGroup()
                        .addGroup(connectionsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel59)
                            .addComponent(jLabel60)
                            .addComponent(jLabel61))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(connectionsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tcSC11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel65)
                            .addComponent(tcSC12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tcSC13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(connectionsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tcSC21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tcSC22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tcSC23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel66)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(connectionsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcSC31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcSC32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcSC33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel67))
                .addGap(78, 78, 78))
        );

        isSellerStorage.setText("Magazynowanie u handlowca ");
        isSellerStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isSellerStorageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(connectionsPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(connectionsPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(calculate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(292, 292, 292)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(suppliersNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sellersNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(customersNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetButton)
                                .addGap(18, 18, 18)
                                .addComponent(isSellerStorage)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(suppliersNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellersNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton)
                    .addComponent(customersNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isSellerStorage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(connectionsPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(connectionsPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(calculate))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        refreshGUI();        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        try {
            ArrayList<Supplier> suppliers = getSuppliersList();
            ArrayList<Customer> customers = getCustomersList();
            TransportConnection[][] transportConnections = getTransportConnectionsMatrix(suppliers, customers);
            SupplyChains solver = new SupplyChains();
            solver.setLogger(getLogger());
            solver.setConnections(transportConnections);
            solver.setCustomers(customers);
            solver.setSuppliers(suppliers);
            solver.solve();
            showResults(solver.getConnectionCosts());
        } catch (SupplyChainsException ex) {
            Logger.getLogger(BrokerProblemWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_calculateActionPerformed

    private void isSellerStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isSellerStorageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isSellerStorageActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransportProblemWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransportProblemWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransportProblemWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransportProblemWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransportProblemWindow().setVisible(true);
            }
        });
    }
    //*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JPanel connectionsPanel3;
    private javax.swing.JPanel connectionsPanel4;
    private javax.swing.JSpinner customersNumber;
    private javax.swing.JSpinner demandO1;
    private javax.swing.JSpinner demandO2;
    private javax.swing.JSpinner demandO3;
    private javax.swing.JSpinner demandSupplyS1;
    private javax.swing.JSpinner demandSupplyS2;
    private javax.swing.JSpinner demandSupplyS3;
    private javax.swing.JCheckBox isSellerStorage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea logArea;
    private javax.swing.JButton resetButton;
    private javax.swing.JSpinner sellersNumber;
    private javax.swing.JSpinner suppliersNumber;
    private javax.swing.JSpinner supplyS1;
    private javax.swing.JSpinner supplyS2;
    private javax.swing.JSpinner supplyS3;
    private javax.swing.JSpinner tcSC11;
    private javax.swing.JSpinner tcSC12;
    private javax.swing.JSpinner tcSC13;
    private javax.swing.JSpinner tcSC21;
    private javax.swing.JSpinner tcSC22;
    private javax.swing.JSpinner tcSC23;
    private javax.swing.JSpinner tcSC31;
    private javax.swing.JSpinner tcSC32;
    private javax.swing.JSpinner tcSC33;
    private javax.swing.JSpinner tcSS11;
    private javax.swing.JSpinner tcSS12;
    private javax.swing.JSpinner tcSS13;
    private javax.swing.JSpinner tcSS21;
    private javax.swing.JSpinner tcSS22;
    private javax.swing.JSpinner tcSS23;
    private javax.swing.JSpinner tcSS31;
    private javax.swing.JSpinner tcSS32;
    private javax.swing.JSpinner tcSS33;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Supplier> getSuppliersList() {
        int n = (int) suppliersNumber.getValue();
        int m = (int) sellersNumber.getValue();
        ArrayList<Supplier> list = new ArrayList();
        for(int i = 0; i < n; i++) {
            Supplier s = new Supplier((int)spinSuppliersSupply[i].getValue(), 0);
            s.isPrivileged = false;
            list.add(s);
        }
        for(int i = 0; i < m; i++) {
            Supplier s = new Supplier((int)spinSellersDemandSupply[i].getValue(), 0);
            s.isPrivileged = false;
            list.add(s);
        }
        return list;
    }

    private ArrayList<Customer> getCustomersList() {  
        int m = (int) sellersNumber.getValue(); 
        int l = (int) customersNumber.getValue();
        ArrayList<Customer> list = new ArrayList();
        for(int i = 0; i < m; i++) {
            Customer c = new Customer((int)spinSellersDemandSupply[i].getValue(), 0);
            c.isPrivileged = false;
            list.add(c);
        }
        for(int i = 0; i < l; i++) {
            Customer c = new Customer((int)spinCustomersDemand[i].getValue(), 0);
            c.isPrivileged = false;
            list.add(c);
        }
        return list;
    }

    private TransportConnection[][] getTransportConnectionsMatrix(ArrayList<Supplier> suppliers, ArrayList<Customer> customers) {
        int HUGE = 1000000;
        int n = (int) suppliersNumber.getValue();
        int m = (int) sellersNumber.getValue();
        int l = (int) customersNumber.getValue();
        int prioritySuSe, prioritySeSe, prioritySeCu;
        if(isSellerStorage.isSelected()) {
            prioritySuSe = TransportConnection.PRIORITY_3;
            prioritySeSe = TransportConnection.PRIORITY_2;
            prioritySeCu = TransportConnection.PRIORITY_1;
        } else {
            prioritySuSe = TransportConnection.PRIORITY_1;
            prioritySeSe = TransportConnection.PRIORITY_2;
            prioritySeCu = TransportConnection.PRIORITY_3;
        }
        /*TODO fakeowy supplier na sztywno - poprawa */
        double demand=0, supply = 0;
        for(Customer c: customers) demand+=c.demand;
        for(Supplier s: suppliers) supply+=s.supply;
        Customer c = new Customer(supply - demand, 0);
        customers.add(c);        
        TransportConnection[][] cons = new TransportConnection[n+m][m+l+1];
        int f = m+l;
        for(int i = 0; i < n + m; i++) {
            cons[i][f] = new TransportConnection(suppliers.get(i), customers.get(f), 0,i,f);
            if((isSellerStorage.isSelected() && i<n) || (!isSellerStorage.isSelected() && i>=n))
                cons[i][f].blocked = true;
            else
                cons[i][f].priority = TransportConnection.PRIORITY_FAKE;
        }
        
        for(int i = 0; i < n; i++) {
            for(int j = 0; j < m; j++) {
                cons[i][j] = new TransportConnection(suppliers.get(i), customers.get(j), (int)spinConnectionsSS[i][j].getValue(),i,j);
                cons[i][j].priority = prioritySuSe;
            }
        }
        for(int i = 0; i < n; i++) {
            for(int j = m; j < m + l; j++) {
                cons[i][j] = new TransportConnection(suppliers.get(i), customers.get(j), 0,i,j);
                cons[i][j].blocked = true;
            }
        }
        for(int i = n; i < n + m; i++) {
            for(int j = 0; j < m; j++) {
                cons[i][j] = new TransportConnection(suppliers.get(i), customers.get(j), 0,i,j);
                if(i - n == j) cons[i][j].priority = prioritySeSe;
                else cons[i][j].blocked = true;
            }
        }
        for(int i = n; i < n + m; i++) {
            for(int j = m; j < m + l; j++) {
                cons[i][j] = new TransportConnection(suppliers.get(i), customers.get(j), (int)spinConnectionsSC[i-n][j-m].getValue(),i,j);
                cons[i][j].priority = prioritySeCu;
            }
        }
        return cons;
    }

    private void showResults(TransportConnection[][] matrix) {
        String results = "\n\n======\nWyniki\n======\n";        
        int N = matrix.length;
        int M = matrix[0].length;
        
        results += "\nIlości:\n";
        for(int i = 0; i < N; i++) {
            for(int j = 0; j < M; j++) {
                results += String.format("%5d", (int)matrix[i][j].amount);
            }
            results += "\n";
        }
        /*
        results += "\nZyski jednoskowe:\n";
        for(int i = 0; i < N; i++) {
            for(int j = 0; j < M; j++) {
                results += String.format("%5d", (int)matrix[i][j].unitProfit());
            }
            results += "\n";
        }
        */
        results += "\n";
        results += "Koszty = " + SupplyChainsUtils.countTotalCosts(matrix);
        results += "\n";
        
        getLogger().info(results);
//        JFrame jf = new JFrame();
//        JTextArea jta = new JTextArea();
//        jta.setText(results);
//        jta.setFont(Font.getFont(Font.SERIF));
//        jf.add(jta);
//        jf.setSize(700, 500);
//        jf.setVisible(true);
    }

    private void refreshGUI() {
        int n = (int) suppliersNumber.getValue();
        int m = (int) sellersNumber.getValue();
        int l = (int) customersNumber.getValue();
        for(int i = 0; i < N; i++) {
            for(int j = 0; j < M; j++) {                
                if(i < n && j < m) spinConnectionsSS[i][j].setEnabled(true);
                else spinConnectionsSS[i][j].setEnabled(false);
            }
        }
        for(int i = 0; i < M; i++) {
            for(int j = 0; j < L; j++) {                
                if(i < m && j < l) spinConnectionsSC[i][j].setEnabled(true);
                else spinConnectionsSC[i][j].setEnabled(false);
            }
        }
        for(int i = 0; i < N; i++) {               
            if(i < n) spinSuppliersSupply[i].setEnabled(true);
            else spinSuppliersSupply[i].setEnabled(false);
        }
        for(int i = 0; i < M; i++) {               
            if(i < m) spinSellersDemandSupply[i].setEnabled(true);
            else spinSellersDemandSupply[i].setEnabled(false);
        }
        for(int i = 0; i < L; i++) {               
            if(i < l) spinCustomersDemand[i].setEnabled(true);
            else spinCustomersDemand[i].setEnabled(false);
        }
    }

    private SupplyChainsLogger getLogger() {
        if(logger != null) return logger;
        logger = new SupplyChainsLogger() {
            @Override
            public void info(String s) {
                logArea.setText(logArea.getText() + s + "\n");
                System.out.println(s);
            }
            
            @Override
            public void error(String s, Exception e) {
                logArea.setText(logArea.getText() + s + "\n");
                logArea.setText(logArea.getText() + e.getMessage() + "\n");
                System.out.println(s);
                System.out.println(e.getMessage());
            }
        };
        return logger;
    }
}
